name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  Setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Virtual env
        run: |
          sudo apt install python3.12-venv
          python3 -m venv venv
          source venv/bin/activate

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd first_pipeline
          pip install -r requirements.txt

      - name: Deploy App
        run: python -m flask --version  # Simple test

      - name: Run Gunicorn
        run: |
          gunicorn -w 4 -b 0.0.0.0:8000 app:app
