name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test Flask App
      run: python -m flask --version  # Simple test

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Clone or update code
          mkdir -p ~/flask-app
          rsync -avz --delete . ~/flask-app
          cd ~/flask-app

          # Set up environment
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          # Run the app with Gunicorn
          pkill gunicorn || true
          gunicorn -w 4 -b 0.0.0.0:8000 app:app --daemon
